// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz2xHfFjigRknu6vpM1XQePcqoofoVmI8',
    appId: '1:350624211725:web:deb32e7fae74532460c644',
    messagingSenderId: '350624211725',
    projectId: 'app-firebase-6926d',
    authDomain: 'app-firebase-6926d.firebaseapp.com',
    databaseURL: 'https://app-firebase-6926d.firebaseio.com',
    storageBucket: 'app-firebase-6926d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSDEgUBs0zhoPO_FsNM7BKquYlpXJOCQ8',
    appId: '1:350624211725:android:19ad3a2c7f7b421360c644',
    messagingSenderId: '350624211725',
    projectId: 'app-firebase-6926d',
    databaseURL: 'https://app-firebase-6926d.firebaseio.com',
    storageBucket: 'app-firebase-6926d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMg0hsHaMnBN4pXjn79_2nTlpatQnhTFk',
    appId: '1:350624211725:ios:2cd80898ab1b674460c644',
    messagingSenderId: '350624211725',
    projectId: 'app-firebase-6926d',
    databaseURL: 'https://app-firebase-6926d.firebaseio.com',
    storageBucket: 'app-firebase-6926d.appspot.com',
    iosClientId: '350624211725-4cvbvtivlms5o0341ujdfeu6rcnikri5.apps.googleusercontent.com',
    iosBundleId: 'com.proscan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMg0hsHaMnBN4pXjn79_2nTlpatQnhTFk',
    appId: '1:350624211725:ios:f5b3c325edc2c23160c644',
    messagingSenderId: '350624211725',
    projectId: 'app-firebase-6926d',
    databaseURL: 'https://app-firebase-6926d.firebaseio.com',
    storageBucket: 'app-firebase-6926d.appspot.com',
    iosClientId: '350624211725-gso1f0eme6l14phpba5ba2g8hvdtuhq9.apps.googleusercontent.com',
    iosBundleId: 'com.wcs.proscan.RunnerTests',
  );
}
